---
title: "class06"
author: "Yutong Wu"
date: "10/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is H1
This is my work from class6 in **BIMM143**.

## This is heading 2

### This is heading 3 etc. 

```{r}
# this is to demo a code chunk 
plot(1:10)
```

#Practice reading files (again...)

```{r}
read.csv("test1.txt")
```
```{r}
read.table("test2.txt",sep="$",header=TRUE)
```
```{r}
read.table("test3.txt",header=TRUE)
```

```{r}
add <- function(x, y=1) {
  
  # Sum the input x and y
  
  x + y
}
```


A new function to re-scale data
```{r}
rescale <- function(x) {
  rng <- range(x)
  (x-rng[1])/(rng[2]-rng[1])
}
```


```{r}
rescale(1:10)
```

```{r}
rescale(c(1,2,NA,3,10))
```

```{r}
x <- c(1,2,NA,3,10)
rng <- range(x, na.rm=TRUE)
```

# Section2 of hands-on sheet

Install the **bio3d** package for sequence and structure analysis 

```{r}
#install.ockages("bio3d")
```

```{r}
library(bio3d) #call the functions in bio3d package
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
# A specific alpha strand on the specific chain of the protein 


s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

#The file that indicates the atom position b at Chain A of the protein 

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor", top = FALSE)
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
#drug affects the mobility of the protein (affect phosphortransferase action)
#Draw a line plot that describes atom postion b at Chain A of each specific protein with optional secondary structure in the marginal regions 
```

```{r}
test<-function(x){
  s1 <- read.pdb(x)
  s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
  s1.b <- s1.chainA$atom$b
  plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
}
```

```{r}
test("4AKE")
test("1AKE")
test("1E4Y")
```















